version: '3'

services:
  rethinkdb:
    image: "rethinkdb"
    expose:
      - 28015
      - 8080
    ports:
      - "28015:28015"
      - "8080:8080"

  setup:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservices:1
    command: ["yarn", "setup"]
    env_file: .env
    depends_on:
      - rethinkdb

  blocks1:
    image: microservices:1
    command: ["npm-run-all", "-s", "setup", "start"]
    environment:
      DUXI_ETH_START_BLOCK: 5000000
      DUXI_ETH_BLOCK_STEP: 3
    env_file: .env
    depends_on:
      - setup
  blocks2:
    image: microservices:1
    command: ["npm-run-all", "-s", "setup", "start"]
    environment:
      DUXI_ETH_START_BLOCK: 5000001
      DUXI_ETH_BLOCK_STEP: 3
    env_file: .env
    depends_on:
      - setup
  blocks3:
    image: microservices:1
    command: ["npm-run-all", "-s", "setup", "start"]
    environment:
      DUXI_ETH_START_BLOCK: 5000002
      DUXI_ETH_BLOCK_STEP: 3
    env_file: .env
    depends_on:
      - setup

  txs:
    image: microservices:1
    command: ["npm-run-all", "-s", "setup", "start-txs"]
    env_file: .env
    depends_on:
      - setup

  receipts:
    image: microservices:1
    command: ["npm-run-all", "-s", "setup", "start-receipts"]
    env_file: .env
    depends_on:
      - setup
      - txs

  contracts:
    image: microservices:1
    command: ["npm-run-all", "-s", "setup", "start-contracts"]
    env_file: .env
    depends_on:
      - setup
      - txs
      - receipts

  transfers:
    image: microservices:1
    command: ["npm-run-all", "-s", "setup", "start-transfers"]
    env_file: .env
    depends_on:
      - setup
      - txs
      - receipts